CREATE TABLE "config" (
	"key" varchar(128) PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "control_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "control_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"kind" varchar(64) NOT NULL,
	"payload" jsonb NOT NULL,
	"consumed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "conversations" (
	"jid" varchar(255) PRIMARY KEY NOT NULL,
	"display_name" text,
	"is_group" boolean DEFAULT false NOT NULL,
	"allowlisted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "incidents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "incidents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"jid" varchar(255),
	"kind" varchar(64) NOT NULL,
	"detail" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"jid" varchar(255) NOT NULL,
	"role" varchar(16) NOT NULL,
	"content" text NOT NULL,
	"tool_calls" jsonb,
	"tool_call_id" text,
	"tool_name" text,
	"model_used" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rate_limits" (
	"jid" varchar(255) NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "rate_limits_jid_window_start_pk" PRIMARY KEY("jid","window_start")
);
--> statement-breakpoint
CREATE TABLE "worker_status" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"connected" boolean DEFAULT false NOT NULL,
	"qr" text,
	"last_heartbeat" timestamp with time zone,
	"last_error" text
);
--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_jid_conversations_jid_fk" FOREIGN KEY ("jid") REFERENCES "public"."conversations"("jid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "messages_jid_created_at_idx" ON "messages" USING btree ("jid","created_at");